/* Demigod service worker. The PRECACHE block is generated by scripts/stamp-sw.mjs. */
/*PRECACHE_START*/
const BUILD = '4e0d6aff34';
const PRECACHE = [
  "assets/fonts/cinzel-latin-700-normal.woff2",
  "assets/fonts/heebo-hebrew-400-normal.woff2",
  "assets/fonts/heebo-hebrew-700-normal.woff2",
  "assets/fonts/heebo-latin-400-normal.woff2",
  "assets/fonts/heebo-latin-700-normal.woff2",
  "assets/icons/apple-touch-icon.png",
  "assets/icons/favicon.svg",
  "assets/icons/icon-192.png",
  "assets/icons/icon-512.png",
  "assets/icons/icon-maskable-512.png",
  "index.html",
  "manifest.webmanifest",
  "offline.html",
  "src/core/achievements.mjs",
  "src/core/backup.mjs",
  "src/core/calendar.mjs",
  "src/core/card.mjs",
  "src/core/charts.mjs",
  "src/core/crew.mjs",
  "src/core/custom.mjs",
  "src/core/draft.mjs",
  "src/core/game.mjs",
  "src/core/gamestate.mjs",
  "src/core/generator.mjs",
  "src/core/i18n.mjs",
  "src/core/live.mjs",
  "src/core/load.mjs",
  "src/core/muscles.mjs",
  "src/core/post.mjs",
  "src/core/profile.mjs",
  "src/core/progression.mjs",
  "src/core/prs.mjs",
  "src/core/quests.mjs",
  "src/core/ranks.mjs",
  "src/core/recovery.mjs",
  "src/core/requests.mjs",
  "src/core/routines.mjs",
  "src/core/search.mjs",
  "src/core/settings.mjs",
  "src/core/shop.mjs",
  "src/core/streak.mjs",
  "src/core/timer.mjs",
  "src/core/views.mjs",
  "src/core/workout.mjs",
  "src/data/achievements.json",
  "src/data/calibration.json",
  "src/data/crew-config.json",
  "src/data/exercises.json",
  "src/data/extra-exercises.json",
  "src/data/i18n/en.json",
  "src/data/i18n/he.json",
  "src/data/muscles.json",
  "src/data/numbers.json",
  "src/data/quests.json",
  "src/data/shop.json",
  "src/main.js",
  "src/styles/base.css",
  "src/styles/components.css",
  "src/styles/tokens.css",
  "src/ui/backup.js",
  "src/ui/calendar.js",
  "src/ui/card-export.js",
  "src/ui/charts.js",
  "src/ui/components.js",
  "src/ui/cosmetics.js",
  "src/ui/crew-api.js",
  "src/ui/crew-state.js",
  "src/ui/crew.js",
  "src/ui/custom.js",
  "src/ui/data.js",
  "src/ui/db.js",
  "src/ui/dom.js",
  "src/ui/emblem.js",
  "src/ui/exercises.js",
  "src/ui/format.js",
  "src/ui/game-ui.js",
  "src/ui/history.js",
  "src/ui/icons.js",
  "src/ui/live.js",
  "src/ui/missing.js",
  "src/ui/muscle-map.js",
  "src/ui/need.js",
  "src/ui/numbers.js",
  "src/ui/onboarding.js",
  "src/ui/picker.js",
  "src/ui/plan-names.js",
  "src/ui/plans.js",
  "src/ui/post-ui.js",
  "src/ui/profile.js",
  "src/ui/progress.js",
  "src/ui/rank-card.js",
  "src/ui/ranks-preview.js",
  "src/ui/ranks.js",
  "src/ui/rename.js",
  "src/ui/requests.js",
  "src/ui/rest-timer.js",
  "src/ui/routines.js",
  "src/ui/screens.js",
  "src/ui/settings.js",
  "src/ui/share.js",
  "src/ui/shop.js",
  "src/ui/storage.js",
  "src/ui/store.js",
  "src/ui/wakelock.js",
  "src/ui/weight-info.js",
  "src/ui/workout.js",
  "src/version.js"
];
/*PRECACHE_END*/

const SHELL_CACHE = `dg-shell-${BUILD}`;
const IMG_CACHE = 'dg-img-v1';
const scope = self.registration.scope;
const u = (p) => new URL(p, scope).href;

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(SHELL_CACHE).then((c) => c.addAll(PRECACHE.map(u))));
  // No skipWaiting here: the page shows a "new version ready" toast and asks first.
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) {
      if (k.startsWith('dg-shell-') && k !== SHELL_CACHE) await caches.delete(k);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('message', (e) => {
  if (e.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      const cache = await caches.open(SHELL_CACHE);
      const isRoot = url.pathname === new URL(scope).pathname || url.pathname.endsWith('/index.html');
      if (isRoot) return (await cache.match(u('index.html'))) ?? fetch(req).catch(() => cache.match(u('offline.html')));
      try { return await fetch(req); }
      catch { return (await cache.match(req)) ?? (await cache.match(u('offline.html'))); }
    })());
    return;
  }

  // Exercise images: cache on first view, refresh in the background.
  if (url.pathname.includes('/assets/exercises/')) {
    e.respondWith((async () => {
      const cache = await caches.open(IMG_CACHE);
      const hit = await cache.match(req);
      const net = fetch(req).then((r) => { if (r.ok) cache.put(req, r.clone()); return r; }).catch(() => hit);
      return hit ?? net;
    })());
    return;
  }

  e.respondWith((async () => {
    const hit = await caches.match(req, { ignoreSearch: true });
    return hit ?? fetch(req);
  })());
});

// Crew notifications (Web Push). The server sends { title, body, tag, url }.
self.addEventListener('push', (e) => {
  let d = {};
  try { d = e.data ? e.data.json() : {}; } catch { d = { body: e.data ? e.data.text() : '' }; }
  e.waitUntil(self.registration.showNotification(d.title || 'Demigod', {
    body: d.body || '', tag: d.tag || 'crew', renotify: true,
    icon: u('assets/icons/icon-192.png'), badge: u('assets/icons/icon-192.png'), data: { url: d.url || '#/crew' },
  }));
});

self.addEventListener('notificationclick', (e) => {
  e.notification.close();
  const hash = e.notification.data?.url || '#/crew';
  e.waitUntil((async () => {
    const all = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const c of all) {
      if ('focus' in c) { await c.focus(); c.postMessage({ type: 'GO', hash }); return; }
    }
    await self.clients.openWindow(u(hash));
  })());
});
