/* Demigod service worker. The PRECACHE block is generated by scripts/stamp-sw.mjs. */
/*PRECACHE_START*/
const BUILD = '4a3c8c4288';
const PRECACHE = [
  "assets/fonts/cinzel-latin-700-normal.woff2",
  "assets/fonts/heebo-hebrew-400-normal.woff2",
  "assets/fonts/heebo-hebrew-700-normal.woff2",
  "assets/fonts/heebo-latin-400-normal.woff2",
  "assets/fonts/heebo-latin-700-normal.woff2",
  "assets/icons/apple-touch-icon.png",
  "assets/icons/favicon.svg",
  "assets/icons/icon-192.png",
  "assets/icons/icon-512.png",
  "assets/icons/icon-maskable-512.png",
  "index.html",
  "manifest.webmanifest",
  "offline.html",
  "src/core/i18n.mjs",
  "src/core/muscles.mjs",
  "src/core/ranks.mjs",
  "src/core/search.mjs",
  "src/core/settings.mjs",
  "src/data/calibration.json",
  "src/data/exercises.json",
  "src/data/i18n/en.json",
  "src/data/i18n/he.json",
  "src/data/muscles.json",
  "src/main.js",
  "src/styles/base.css",
  "src/styles/components.css",
  "src/styles/tokens.css",
  "src/ui/components.js",
  "src/ui/data.js",
  "src/ui/dom.js",
  "src/ui/emblem.js",
  "src/ui/exercises.js",
  "src/ui/icons.js",
  "src/ui/muscle-map.js",
  "src/ui/ranks-preview.js",
  "src/ui/screens.js",
  "src/ui/storage.js",
  "src/version.js"
];
/*PRECACHE_END*/

const SHELL_CACHE = `dg-shell-${BUILD}`;
const IMG_CACHE = 'dg-img-v1';
const scope = self.registration.scope;
const u = (p) => new URL(p, scope).href;

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(SHELL_CACHE).then((c) => c.addAll(PRECACHE.map(u))));
  // No skipWaiting here: the page shows a "new version ready" toast and asks first.
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) {
      if (k.startsWith('dg-shell-') && k !== SHELL_CACHE) await caches.delete(k);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('message', (e) => {
  if (e.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      const cache = await caches.open(SHELL_CACHE);
      const isRoot = url.pathname === new URL(scope).pathname || url.pathname.endsWith('/index.html');
      if (isRoot) return (await cache.match(u('index.html'))) ?? fetch(req).catch(() => cache.match(u('offline.html')));
      try { return await fetch(req); }
      catch { return (await cache.match(req)) ?? (await cache.match(u('offline.html'))); }
    })());
    return;
  }

  // Exercise images: cache on first view, refresh in the background.
  if (url.pathname.includes('/assets/exercises/')) {
    e.respondWith((async () => {
      const cache = await caches.open(IMG_CACHE);
      const hit = await cache.match(req);
      const net = fetch(req).then((r) => { if (r.ok) cache.put(req, r.clone()); return r; }).catch(() => hit);
      return hit ?? net;
    })());
    return;
  }

  e.respondWith((async () => {
    const hit = await caches.match(req, { ignoreSearch: true });
    return hit ?? fetch(req);
  })());
});
