// OUR CALIBRATION. Anchor R = 1RM (kg) an 80 kg male needs for rating 900 (start of Olympian) on that family's anchor lift.
// Per-exercise R = family R x ratio (ratio lives next to the exercise in the curation files, then in src/data/calibration.json).
// perHand: weights are entered per hand. bwFactor: share of bodyweight that counts as load.
export const FAMILIES = {
  // chest
  'bench-flat': { R: 225, note: 'Barbell bench press (seed anchor)' },
  'bench-incline': { R: 190, note: 'Incline barbell bench (seed anchor)' },
  'db-bench': { R: 90, perHand: true, note: 'Dumbbell bench press (seed anchor)' },
  'db-incline': { R: 78, perHand: true, note: 'Incline dumbbell press (seed anchor)' },
  'chest-machine': { R: 215, note: 'Machine chest press (seed anchor)' },
  'chest-cable-press': { R: 118, note: 'Cable chest press: about 0.55 of the machine press' },
  'fly-db': { R: 38, perHand: true, note: 'Dumbbell fly: about 0.42 of the dumbbell press' },
  'fly-cable': { R: 70, note: 'Cable fly / crossover, weight shown per side' },
  'pec-deck': { R: 150, note: 'Pec deck / butterfly machine' },
  dip: { R: 200, bwFactor: 0.95, note: 'Dips (seed anchor)' },
  pushup: { R: 220, bwFactor: 0.64, note: 'Push-up (seed anchor)' },
  'pullover-db': { R: 70, perHand: true, note: 'Dumbbell pullover (one dumbbell, both hands)' },
  'pullover-bb': { R: 85, note: 'Barbell pullover' },
  // back
  deadlift: { R: 330, note: 'Deadlift (seed anchor)' },
  'rack-pull': { R: 360, note: 'Rack pull: partial range, heavier than the floor deadlift' },
  hyperextension: { R: 170, bwFactor: 0.4, note: 'Back extension: bodyweight share plus added plate' },
  'row-barbell': { R: 200, note: 'Barbell row (seed anchor)' },
  'row-db': { R: 95, perHand: true, note: 'Dumbbell row (seed anchor)' },
  'row-cable': { R: 190, note: 'Seated cable row (seed anchor)' },
  'row-machine': { R: 200, note: 'Plate/stack row machine' },
  'row-bodyweight': { R: 200, bwFactor: 0.55, note: 'Inverted / suspended row' },
  pulldown: { R: 190, note: 'Lat pulldown (seed anchor)' },
  'straight-arm': { R: 90, note: 'Straight-arm pulldown' },
  pullup: { R: 260, bwFactor: 1, note: 'Pull-up (seed anchor)' },
  chinup: { R: 270, bwFactor: 1, note: 'Chin-up (seed anchor)' },
  'shrug-bb': { R: 240, note: 'Barbell shrug' },
  'shrug-db': { R: 110, perHand: true, note: 'Dumbbell shrug' },
  clean: { R: 150, note: 'Power clean / hang clean' },
  // shoulders
  ohp: { R: 140, note: 'Overhead press (seed anchor)' },
  'db-press-shoulder': { R: 65, perHand: true, note: 'Dumbbell shoulder press (seed anchor)' },
  'machine-shoulder': { R: 150, note: 'Machine shoulder press (seed anchor)' },
  'cable-press-shoulder': { R: 85, note: 'Cable shoulder press' },
  'push-press': { R: 160, note: 'Push press: about 1.15 of the strict press' },
  'lateral-raise': { R: 40, perHand: true, note: 'Lateral raise (seed anchor)' },
  'front-raise': { R: 40, perHand: true, note: 'Front raise' },
  'rear-delt-db': { R: 30, perHand: true, note: 'Dumbbell rear delt raise' },
  'rear-delt-machine': { R: 110, note: 'Reverse fly machine' },
  'rear-delt-cable': { R: 55, note: 'Cable rear delt fly' },
  'face-pull': { R: 130, note: 'Face pull (seed anchor)' },
  'upright-row': { R: 130, note: 'Upright row' },
  // arms
  'curl-bb': { R: 115, note: 'Barbell curl (seed anchor)' },
  'curl-db': { R: 52, perHand: true, note: 'Dumbbell curl (seed anchor)' },
  hammer: { R: 55, perHand: true, note: 'Hammer curl (seed anchor)' },
  'curl-cable': { R: 105, note: 'Cable curl' },
  'curl-machine': { R: 120, note: 'Machine / preacher machine curl' },
  pushdown: { R: 130, note: 'Triceps pushdown (seed anchor)' },
  skull: { R: 115, note: 'Skull crusher (seed anchor)' },
  overhead: { R: 75, note: 'Overhead triceps extension (seed anchor)' },
  'tri-kickback': { R: 28, perHand: true, note: 'Dumbbell kickback' },
  'close-grip': { R: 190, note: 'Close-grip bench (seed anchor)' },
  'tri-machine': { R: 140, note: 'Seated triceps machine' },
  'bench-dip': { R: 170, bwFactor: 0.4, note: 'Bench dip: partial bodyweight plus lap weight' },
  // legs
  squat: { R: 290, note: 'Back squat (seed anchor)' },
  'front-squat': { R: 240, note: 'Front squat (seed anchor)' },
  'leg-press': { R: 650, note: 'Leg press (seed anchor)' },
  'hack-machine': { R: 420, note: 'Hack squat (seed anchor)' },
  'leg-extension': { R: 190, note: 'Leg extension (seed anchor)' },
  'lunge-bb': { R: 200, note: 'Barbell lunge: about 0.7 of the squat' },
  'lunge-db': { R: 85, perHand: true, note: 'Dumbbell lunge' },
  'stepup-db': { R: 80, perHand: true, note: 'Dumbbell step-up / split squat' },
  rdl: { R: 300, note: 'Romanian deadlift (seed anchor)' },
  'leg-curl': { R: 140, note: 'Leg curl (seed anchor)' },
  'glute-ham': { R: 190, bwFactor: 0.5, note: 'Glute-ham raise: half the bodyweight plus plate' },
  'good-morning': { R: 180, note: 'Good morning' },
  'hip-thrust': { R: 350, note: 'Hip thrust (seed anchor)' },
  'cable-glute': { R: 60, note: 'Cable kickback, weight on the stack per leg' },
  'pull-through': { R: 130, note: 'Cable pull-through' },
  'hip-abduction': { R: 200, note: 'Hip abduction machine' },
  'reverse-hyper': { R: 220, note: 'Reverse hyperextension machine' },
  'calf-standing': { R: 320, note: 'Standing calf raise (seed anchor)' },
  'calf-seated': { R: 200, note: 'Seated calf raise' },
  'calf-press': { R: 450, note: 'Calf press on a leg press' },
  // abs
  'cable-crunch': { R: 150, note: 'Cable crunch (seed anchor)' },
  'ab-machine': { R: 160, note: 'Ab crunch machine' },
  'cable-rotation': { R: 80, note: 'Cable wood chop / twist / lift' },
  'side-bend-db': { R: 60, perHand: true, note: 'Dumbbell side bend' },
  'side-bend-bb': { R: 120, note: 'Barbell side bend' },
  pallof: { R: 70, note: 'Pallof press' },
};
