// Display names of the calibration families: [English, עברית]
export const FAMILY_NAMES = {
  'bench-flat': ['Barbell bench press', 'לחיצת חזה עם מוט'], 'bench-incline': ['Incline barbell press', 'לחיצת חזה משופעת עם מוט'],
  'db-bench': ['Dumbbell bench press', 'לחיצת חזה עם משקולות'], 'db-incline': ['Incline dumbbell press', 'לחיצת חזה משופעת עם משקולות'],
  'chest-machine': ['Machine chest press', 'לחיצת חזה במכונה'], 'chest-cable-press': ['Cable chest press', 'לחיצת חזה בכבלים'],
  'fly-db': ['Dumbbell fly', 'פרפר עם משקולות'], 'fly-cable': ['Cable fly', 'פרפר בכבלים'], 'pec-deck': ['Pec deck', 'פרפר במכונה'],
  dip: ['Dips', 'מקבילים'], pushup: ['Push-up', 'שכיבות סמיכה'], 'pullover-db': ['Dumbbell pullover', 'פולאובר עם משקולת'], 'pullover-bb': ['Barbell pullover', 'פולאובר עם מוט'],
  deadlift: ['Deadlift', 'דדליפט'], 'rack-pull': ['Rack pull', 'רק פול'], hyperextension: ['Back extension', 'פשיטת גב'],
  'row-barbell': ['Barbell row', 'חתירה עם מוט'], 'row-db': ['Dumbbell row', 'חתירה עם משקולת'], 'row-cable': ['Seated cable row', 'חתירה בכבל'],
  'row-machine': ['Machine row', 'חתירה במכונה'], 'row-bodyweight': ['Inverted row', 'חתירה הפוכה'], pulldown: ['Lat pulldown', 'משיכת פולי עליון'],
  'straight-arm': ['Straight-arm pulldown', 'משיכה בזרועות ישרות'], pullup: ['Pull-up', 'מתח'], chinup: ['Chin-up', 'מתח באחיזה הפוכה'],
  'shrug-bb': ['Barbell shrug', 'משיכות כתפיים עם מוט'], 'shrug-db': ['Dumbbell shrug', 'משיכות כתפיים עם משקולות'], clean: ['Power clean', 'פאוור קלין'],
  ohp: ['Overhead press', 'לחיצת כתפיים עם מוט'], 'db-press-shoulder': ['Dumbbell shoulder press', 'לחיצת כתפיים עם משקולות'],
  'machine-shoulder': ['Machine shoulder press', 'לחיצת כתפיים במכונה'], 'cable-press-shoulder': ['Cable shoulder press', 'לחיצת כתפיים בכבלים'],
  'push-press': ['Push press', 'פוש פרס'], 'lateral-raise': ['Lateral raise', 'הרמות צד'], 'front-raise': ['Front raise', 'הרמות קדמיות'],
  'rear-delt-db': ['Rear delt raise', 'הרמה לכתף אחורית'], 'rear-delt-machine': ['Reverse fly machine', 'פרפר הפוך במכונה'], 'rear-delt-cable': ['Cable rear delt fly', 'פרפר הפוך בכבלים'],
  'face-pull': ['Face pull', 'פייס פול'], 'upright-row': ['Upright row', 'משיכה לסנטר'],
  'curl-bb': ['Barbell curl', 'כפיפת מרפקים עם מוט'], 'curl-db': ['Dumbbell curl', 'כפיפת מרפקים עם משקולות'], hammer: ['Hammer curl', 'כפיפות פטיש'],
  'curl-cable': ['Cable curl', 'כפיפת מרפקים בכבל'], 'curl-machine': ['Machine curl', 'כפיפת מרפקים במכונה'],
  pushdown: ['Triceps pushdown', 'פשיטת מרפקים בפולי'], skull: ['Skull crusher', 'סקאל קראשר'], overhead: ['Overhead triceps extension', 'פשיטת מרפקים מעל הראש'],
  'tri-kickback': ['Triceps kickback', 'בעיטה לאחור'], 'close-grip': ['Close-grip bench', 'לחיצת חזה באחיזה צרה'], 'tri-machine': ['Triceps machine', 'מכונת תלת ראשי'], 'bench-dip': ['Bench dip', 'מקבילים על ספסל'],
  squat: ['Back squat', 'סקוואט'], 'front-squat': ['Front squat', 'סקוואט קדמי'], 'leg-press': ['Leg press', 'לחיצת רגליים'], 'hack-machine': ['Hack squat', 'האק סקוואט'],
  'leg-extension': ['Leg extension', 'פשיטת ברכיים'], 'lunge-bb': ['Barbell lunge', 'מכרעים עם מוט'], 'lunge-db': ['Dumbbell lunge', 'מכרעים עם משקולות'], 'stepup-db': ['Dumbbell step-up', 'עליות על ספסל עם משקולות'],
  rdl: ['Romanian deadlift', 'דדליפט רומני'], 'leg-curl': ['Leg curl', 'כפיפת ברכיים'], 'glute-ham': ['Glute-ham raise', 'גלוט האם רייז'], 'good-morning': ['Good morning', 'גוד מורנינג'],
  'hip-thrust': ['Hip thrust', 'היפ טראסט'], 'cable-glute': ['Cable kickback', 'בעיטה לאחור בכבל'], 'pull-through': ['Cable pull-through', 'משיכה בין הרגליים בכבל'],
  'hip-abduction': ['Hip abduction', 'הרחקת ירכיים'], 'reverse-hyper': ['Reverse hyperextension', 'היפראקסטנשן הפוך'],
  'calf-standing': ['Standing calf raise', 'הרמות תאומים בעמידה'], 'calf-seated': ['Seated calf raise', 'הרמות תאומים בישיבה'], 'calf-press': ['Calf press', 'לחיצת תאומים'],
  'cable-crunch': ['Cable crunch', 'כפיפות בטן בכבל'], 'ab-machine': ['Ab machine', 'מכונת בטן'], 'cable-rotation': ['Cable rotation', 'סיבוב בכבל'],
  'side-bend-db': ['Dumbbell side bend', 'כפיפה לצד עם משקולת'], 'side-bend-bb': ['Barbell side bend', 'כפיפה לצד עם מוט'], pallof: ['Pallof press', 'פאלוף פרס'],
};
